name: My Custom Action
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: true
        default: dev
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      shell: bash
      run: |
        echo "Environment: ${{ inputs.environment }}"
