name: My Custom Action
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: true
        default: dev
        type: choice
        options:
          - prod
          - staging
          - qa
      artifact_tag: 
        description: select git tag to deploy
        required: true
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: |
        echo "Deploying the ${{inputs.artifact_tag}} app into ${{ inputs.environment }}"
