name: system-info
on: workflow_dispatch
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: info
        run: | 
          echo "this is durgaprasad"
          echo "here i am"
          date
          hostname
          free -m
        
  
