name: system-info
on: workflow_dispatch
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: runner
        run: echo "checking..."
  build: 
    runs-on: 
    steps:
      - name: building
        run: echo "building..."
  test:
    runs-on: 
    needs: build
    steps:
      - name: testing
        run: echo "test cases...."
  deploy:
    runs-on: 
    steps:
      - name: deploy
        run: echo "deploying app"
